[package]
name = "rustieraServer"
version = "0.1.0"
edition = "2024"

[dependencies]
quiche = "*"
log = "*"
env_logger="*"
backtrace = "*"
tokio = { version = "*",features = ["full"] }
mio = { version = "*", features = ["os-poll","net"] }
ring = "0.16.20"
libRustiera = { path = "../libRustiera" }
